name: Linkinator CI

on:
  schedule:
    - cron: '0 0 * * 0'  # This will run every Sunday at midnight

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # specify the Node.js version

      - name: Install linkinator
        run: npm install -g linkinator

      - name: Run linkinator
        run: npx linkinator https://docs.codat.io --recurse
